# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

collections:
    tabs:
        output: true
        permalink: /tabs/:path/

defaults:
    scope:
      path: "" # empty string for all files
    values:
      title: "Some title"

description: Just another blog about frontend and web stuff...

author:
  name: Pascal Boutin
  email: pboutin@webcliniq.com
  github: pboutin
  linkedin: ca.linkedin.com/pub/pascal-boutin/62/370/447/
  email_md5: f39075d6c30e8e91db9390a6b1b97e27

rss_path: feed.xml
